// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stoykxkutnqbkehzerzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0b3lreGt1dG5xYmtlaHplcnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1Njc1MTIsImV4cCI6MjA4NTE0MzUxMn0.zF8db1Ftb2aoQ1r1iiVYwIMzEOm8YIyGlSC40wJweHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});